language: go

go:
  - "1.13"
  - "1.14"

install:
  - cd ./full-text
  - go mod tidy
  - go build

script:
  - cd ./full-text
  - go mod tidy
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
