---
version: "3.7"
services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
    - 9200:9200
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - elastic-data:/usr/share/elasticsearch/data

  manticore:
    image: manticoresearch/manticore:3.3.0
    ports:
    - 9306:9306
    volumes:
    - ./manticore.conf:/etc/sphinxsearch/sphinx.conf
    - manticore-data:/var/lib/manticore/data

  sphinx:
    image: macbre/sphinxsearch:3.0.3
    ports:
    - 9307:9306
    volumes:
    - ./sphinx.conf:/opt/sphinx/conf/sphinx.conf
    - sphinx-data:/var/lib/sphinxsearch/data

volumes:
  elastic-data:
  manticore-data:
  sphinx-data:
